import { useState, useCallback } from 'react';

/**
 * Custom Hook for Google Services Integration / Simulation
 * Now features a robust .ics fallback to ensure "Add to Calendar" is functionally real.
 */
export const useGoogleIntegration = () => {
  const [syncing, setSyncing] = useState(false);
  const [statusMessage, setStatusMessage] = useState(null);

  /**
   * Generates and downloads an iCalendar (.ics) file.
   * This provides an immediate, functional fallback that works with Google, 
   * Outlook, and Apple calendars without needing a live API server.
   */
  const generateICS = (roadmap) => {
    let icsContent = "BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//AI Career Copilot//Strategic Roadmap//EN\n";
    
    const now = new Date();
    
    roadmap.forEach((step, index) => {
      // Schedule events starting tomorrow, 9:00 AM
      const eventDate = new Date(now);
      eventDate.setDate(now.getDate() + index + 1);
      
      const year = eventDate.getFullYear();
      const month = String(eventDate.getMonth() + 1).padStart(2, '0');
      const day = String(eventDate.getDate()).padStart(2, '0');
      
      const dateStr = `${year}${month}${day}`;
      
      icsContent += "BEGIN:VEVENT\n";
      icsContent += `DTSTART;VALUE=DATE:${dateStr}T090000\n`;
      icsContent += `DTEND;VALUE=DATE:${dateStr}T120000\n`;
      icsContent += `SUMMARY:Career Focus: ${step.task}\n`;
      icsContent += `DESCRIPTION:Strategic milestone generated by AI Career Copilot. Task: ${step.task}\n`;
      icsContent += "END:VEVENT\n";
    });

    icsContent += "END:VCALENDAR";

    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', 'Career-Roadmap-Schedule.ics');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  /**
   * Simulate / Execute Calendar Sync
   */
  const addToCalendar = useCallback(async (roadmap) => {
    setSyncing(true);
    setStatusMessage({ type: 'info', text: 'Preparing Strategic Schedule...' });

    return new Promise((resolve) => {
      setTimeout(() => {
        // Execute the real .ics download for immediate utility
        generateICS(roadmap);
        
        setSyncing(false);
        setStatusMessage({ 
          type: 'success', 
          text: `Success! ${roadmap.length} focus blocks generated. Import the downloaded file to your calendar.` 
        });
        resolve(true);
      }, 1500);
    });
  }, []);

  const saveToDrive = useCallback(async (plan) => {
    setSyncing(true);
    setStatusMessage({ type: 'info', text: 'Archiving Strategy to Drive...' });

    return new Promise((resolve) => {
      setTimeout(() => {
        setSyncing(false);
        setStatusMessage({ 
          type: 'success', 
          text: `Roadmap archived! Simulated sync complete.` 
        });
        resolve(true);
      }, 2000);
    });
  }, []);

  const clearMessage = () => setStatusMessage(null);

  return {
    syncing,
    message: statusMessage,
    addToCalendar,
    saveToDrive,
    clearMessage
  };
};
