/**
 * Exporter utility to handle file generating and browser downloads.
 */

/**
 * Formats career plan data into a clean, readable text string
 */
export const formatPlanAsText = (plan) => {
  const divider = "================================================\n";
  const subDivider = "------------------------------------------------\n";

  let content = `AI CAREER COPILOT - STRATEGIC REPORT\n`;
  content += `Ready Tier: ${plan.level} (${plan.score}% Mastery)\n`;
  content += divider + "\n";

  content += `0. STRATEGY RATIONALE (AI INSIGHTS)\n`;
  content += subDivider;
  content += `• Placement: ${plan.insights.placement}\n`;
  content += `• Curation: ${plan.insights.curation}\n`;
  content += `• Pacing: ${plan.insights.pacing}\n`;
  content += "\n";

  content += `1. CRITICAL SKILL GAPS\n`;
  content += subDivider;
  plan.skillGap.forEach(skill => {
    content += `• ${skill}\n`;
  });
  content += "\n";

  content += `2. RECOMMENDED LEARNING PRIORITIES\n`;
  content += subDivider;
  plan.recommendedSkills.forEach(skill => {
    content += `• ${skill}\n`;
  });
  content += "\n";

  content += `3. INTENSIVE EXECUTION ROADMAP\n`;
  content += subDivider;
  plan.roadmap.forEach(step => {
    content += `DAY ${step.day}: ${step.task}\n`;
  });
  content += "\n";

  content += `4. SUGGESTED VALIDATION PROJECTS\n`;
  content += subDivider;
  plan.projects.forEach(project => {
    content += `• ${project.name} (${project.tech})\n`;
  });
  content += "\n";

  content += `5. CANDIDATE INTELLIGENCE TIPS\n`;
  content += subDivider;
  plan.resumeTips.forEach(tip => {
    content += `• ${tip.text}\n`;
  });
  content += "\n" + divider;
  content += `Generated by AI Career Copilot on ${new Date().toLocaleDateString()}\n`;

  return content;
};

/**
 * Triggers a browser download of a text string as a file
 */
export const downloadTextFile = (content, filename = 'AI-Career-Plan.txt') => {
  // Use UTF-8 with BOM for better Windows/Excel/Notepad compatibility
  const blob = new Blob(["\ufeff", content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  
  // Ensure visibility for some browser security contexts
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  
  // Cleanup
  setTimeout(() => {
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }, 100);
};
